import { createFileRoute, useRouter } from "@tanstack/react-router";
import { ArrowDown, ArrowUp, Check, ImagePlus, LogOut, Pencil, Trash2, X } from "lucide-react";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
import { validateImage } from "@/lib/site";

export const Route = createFileRoute("/_authenticated/dashboard")({
  head: () => ({ meta: [{ title: "Dashboard | AL-ANWAR Build & Design" }, { name: "description", content: "Manage AL-ANWAR projects, reviews, and enquiries." }, { property: "og:title", content: "AL-ANWAR Admin Dashboard" }, { property: "og:description", content: "Private business content management." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }, { name: "robots", content: "noindex" }] }),
  component: Dashboard,
});

type Project = { id:string; title:string; alt_text:string; image_path:string; sort_order:number; image_url:string };
type Review = { id:string; customer_name:string; rating:number; review_text:string; photo_path:string|null; status:"pending"|"approved"|"rejected"; created_at:string; photo_url:string|null };
type Enquiry = { id:string; customer_name:string; phone:string; service:string; message:string; created_at:string };

function Dashboard() {
  const router = useRouter(); const [tab,setTab]=useState("projects"); const [projects,setProjects]=useState<Project[]>([]); const [reviews,setReviews]=useState<Review[]>([]); const [enquiries,setEnquiries]=useState<Enquiry[]>([]); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState(false);
  async function load() {
    const [{data:p},{data:r},{data:e}] = await Promise.all([supabase.from("projects").select("*").order("sort_order"),supabase.from("reviews").select("*").order("created_at",{ascending:false}),supabase.from("enquiries").select("*").order("created_at",{ascending:false})]);
    const pp=await Promise.all((p??[]).map(async x=>({...x,image_url:(await supabase.storage.from("project-photos").createSignedUrl(x.image_path,3600)).data?.signedUrl ?? ""})));
    const rr=await Promise.all((r??[]).map(async x=>({...x,photo_url:x.photo_path ? ((await supabase.storage.from("review-photos").createSignedUrl(x.photo_path,3600)).data?.signedUrl ?? null) : null})));
    setProjects(pp); setReviews(rr); setEnquiries(e??[]);
  }
  useEffect(()=>{void load()},[]);
  async function upload(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setNotice("");const f=new FormData(event.currentTarget);const files=f.getAll("photos") as File[];for(const [i,file] of files.entries()){const issue=validateImage(file,10);if(issue){setNotice(issue);setBusy(false);return}const path=`projects/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const up=await supabase.storage.from("project-photos").upload(path,file,{contentType:file.type});if(up.error){setNotice("An image could not be uploaded.");setBusy(false);return}await supabase.from("projects").insert({title:String(f.get("title")||"Project"),alt_text:String(f.get("alt")||"AL-ANWAR completed project"),image_path:path,sort_order:projects.length+i})}event.currentTarget.reset();await load();setNotice("Project photos added.");setBusy(false)}
  async function removeProject(p:Project){if(!confirm("Delete this project photo?"))return;await supabase.from("projects").delete().eq("id",p.id);await supabase.storage.from("project-photos").remove([p.image_path]);await load()}
  async function replaceProject(p:Project,file:File|undefined){if(!file)return;const issue=validateImage(file,10);if(issue){setNotice(issue);return}setBusy(true);const path=`projects/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const uploadResult=await supabase.storage.from("project-photos").upload(path,file,{contentType:file.type});if(uploadResult.error){setNotice("The replacement image could not be uploaded.");setBusy(false);return}const {error}=await supabase.from("projects").update({image_path:path}).eq("id",p.id);if(error){await supabase.storage.from("project-photos").remove([path]);setNotice("The project image could not be replaced.");setBusy(false);return}await supabase.storage.from("project-photos").remove([p.image_path]);await load();setNotice("Project image replaced.");setBusy(false)}
  async function move(p:Project,by:number){const idx=projects.findIndex(x=>x.id===p.id);const other=projects[idx+by];if(!other)return;await Promise.all([supabase.from("projects").update({sort_order:other.sort_order}).eq("id",p.id),supabase.from("projects").update({sort_order:p.sort_order}).eq("id",other.id)]);await load()}
  async function reviewStatus(review:Review,status:Review["status"]){await supabase.from("reviews").update({status,updated_at:new Date().toISOString()}).eq("id",review.id);await load()}
  async function editReview(review:Review){const text=prompt("Edit review text",review.review_text);if(!text||text.trim().length<5)return;await supabase.from("reviews").update({review_text:text.trim(),updated_at:new Date().toISOString()}).eq("id",review.id);await load()}
  async function removeReview(review:Review){if(!confirm("Delete this review permanently?"))return;await supabase.from("reviews").delete().eq("id",review.id);if(review.photo_path)await supabase.storage.from("review-photos").remove([review.photo_path]);await load()}
  async function signOut(){await supabase.auth.signOut();await router.navigate({to:"/admin",replace:true})}
  const nav: Array<[string,string]>=[['projects','Project Photos'],['pending','Pending Reviews'],['approved','Approved Reviews'],['rejected','Rejected Reviews'],['enquiries','Customer Enquiries']];
  return <main className="min-h-screen bg-muted/40"><header className="border-b bg-ink text-primary-foreground"><div className="section-shell flex min-h-20 items-center justify-between gap-4"><div><p className="eyebrow">AL-ANWAR</p><h1 className="text-2xl">Content Dashboard</h1></div><Button variant="glass" onClick={signOut}><LogOut/>Logout</Button></div></header><div className="section-shell py-8"><div className="mb-8 flex gap-2 overflow-x-auto pb-2">{nav.map(([id,label])=><Button key={id} variant={tab===id?'default':'outline'} onClick={()=>setTab(id)} className="shrink-0">{label}{id==='pending'&&` (${reviews.filter(r=>r.status==='pending').length})`}</Button>)}</div>
  {tab==='projects'&&<section><form onSubmit={upload} className="mb-8 grid gap-4 rounded-md bg-card p-6 shadow-sm sm:grid-cols-2"><div><Label>Project title</Label><Input name="title" required maxLength={120} className="mt-2"/></div><div><Label>Image description</Label><Input name="alt" required maxLength={180} className="mt-2"/></div><div className="sm:col-span-2"><Label>Project photos</Label><Input name="photos" type="file" accept="image/*" multiple required className="mt-2"/></div><Button disabled={busy} className="sm:justify-self-start"><ImagePlus/>{busy?'Uploading…':'Upload photos'}</Button></form>{notice&&<p className="mb-5 text-sm">{notice}</p>}<div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{projects.map(p=><article key={p.id} className="overflow-hidden rounded-md bg-card shadow-sm"><img src={p.image_url} alt={p.alt_text} className="aspect-[4/3] w-full object-cover"/><div className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-2 p-4"><b className="truncate">{p.title}</b><div className="flex gap-2"><Input id={`replace-${p.id}`} type="file" accept="image/*" className="sr-only" onChange={(event)=>void replaceProject(p,event.target.files?.[0])}/><Button size="icon" variant="outline" onClick={()=>document.getElementById(`replace-${p.id}`)?.click()} aria-label="Replace image"><ImagePlus/></Button><Button size="icon" variant="outline" onClick={()=>move(p,-1)} aria-label="Move earlier"><ArrowUp/></Button><Button size="icon" variant="outline" onClick={()=>move(p,1)} aria-label="Move later"><ArrowDown/></Button><Button size="icon" variant="destructive" onClick={()=>removeProject(p)} aria-label="Delete"><Trash2/></Button></div></div></article>)}</div></section>}
  {['pending','approved','rejected'].includes(tab)&&<section className="space-y-4">{reviews.filter(r=>r.status===tab).map(r=><article key={r.id} className="rounded-md bg-card p-6 shadow-sm"><div className="grid grid-cols-[minmax(0,1fr)_auto] gap-4"><div className="min-w-0"><h2 className="truncate text-xl">{r.customer_name} · {r.rating}/5</h2><p className="mt-2 text-sm leading-6">{r.review_text}</p><time className="mt-3 block text-xs text-muted-foreground">{new Date(r.created_at).toLocaleString()}</time></div>{r.photo_url&&<img src={r.photo_url} alt="Customer" className="h-16 w-16 shrink-0 rounded-full object-cover"/>}</div><div className="mt-5 flex flex-wrap gap-2"><Button variant="outline" onClick={()=>editReview(r)}><Pencil/>Edit</Button>{r.status!=='approved'&&<Button onClick={()=>reviewStatus(r,'approved')}><Check/>Approve</Button>}{r.status!=='rejected'&&<Button variant="secondary" onClick={()=>reviewStatus(r,'rejected')}><X/>Reject</Button>}<Button variant="destructive" onClick={()=>removeReview(r)}><Trash2/>Delete</Button></div></article>)}</section>}
  {tab==='enquiries'&&<section className="space-y-4">{enquiries.map(e=><article key={e.id} className="rounded-md bg-card p-6 shadow-sm"><div className="grid grid-cols-[minmax(0,1fr)_auto] gap-4"><div className="min-w-0"><h2 className="truncate text-xl">{e.customer_name}</h2><a href={`tel:${e.phone}`} className="text-sm text-primary">{e.phone}</a><p className="mt-1 text-xs font-semibold uppercase text-muted-foreground">{e.service}</p><p className="mt-4 leading-7">{e.message}</p><time className="mt-3 block text-xs text-muted-foreground">{new Date(e.created_at).toLocaleString()}</time></div><Button size="icon" variant="destructive" aria-label="Delete enquiry" onClick={async()=>{if(confirm('Delete this enquiry?')){await supabase.from('enquiries').delete().eq('id',e.id);await load()}}}><Trash2/></Button></div></article>)}</section>}
  </div></main>;
}